export {
  createAuth,
  AuthProvider,
  ProtectedRoute,
  useSession,
  AuthContext,
  Credentials,
  Google,
  createMemoryStorage,
  createLocalStorageAdapter,
  AuthError,
  ACCESS_TOKEN_EXPIRY_FALLBACK_MS,
  ACCESS_TOKEN_EXPIRY_SAFETY_BUFFER_MS,
  decodeJwtPayload,
  getAccessTokenExpiry,
} from './types/auth.js';

export type {
  MaybePromise,
  AuthStatus,
  AuthUser,
  AuthSession,
  AuthStorage,
  AuthErrorOptions,
  ProviderContext,
  AuthProviderConfig,
  CredentialField,
  CredentialsConfig,
  GoogleInput,
  GoogleConfig,
  RefreshContext,
  AuthConfig,
  GetSessionOptions,
  RefreshOptions,
  AuthClient,
  AuthProviderProps,
  ProtectedRouteProps,
  LocalStorageAdapterOptions,
  AccessTokenExpiryOptions,
} from './types/auth.js';
