export {
  createAuthSdk,
  GoogleSignIn,
  AppleSignIn,
  GitHubSignIn,
  getGoogleIdToken,
  getAppleCredential,
  getGitHubAuthorization,
  completeGitHubSignIn,
  GITHUB_CALLBACK_MESSAGE,
  loadScript,
  createOAuthState,
  openCenteredPopup,
  waitForPopupMessage,
  AuthSdkError,
} from './types/auth-sdk.js';

export type {
  AuthSdkErrorOptions,
  GoogleSdkConfig,
  AppleSdkConfig,
  GitHubSdkConfig,
  AuthSdkEndpoints,
  AuthSdkConfig,
  GoogleSignInInput,
  AppleSignInInput,
  AppleCredential,
  GitHubSignInInput,
  GitHubAuthorization,
  AuthSdkClient,
  SignInProviderOptions,
  ScriptLoadOptions,
  PopupOptions,
  PopupMessageOptions,
  OAuthCallbackMessage,
} from './types/auth-sdk.js';
